title: Mozilla Chile
description: Por un internet público, libre y accesible.
extradescription: Medio de difusión de actividades de Mozilla Chile
email: release-mgmt@mozilla.com
url: "https://mozillachile.cl"
github: "https://github.com/mozilla/release-blog"
highlighter: rouge
repository: https://github.com/mozillachile/blog

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

# Navigation
navigation:
- title: Twitter
  url: https://twitter.com/MozillaReleases
- title: Team Wiki
  url: https://wiki.mozilla.org/Release_Management
- title: Release Calendar
  url: https://wiki.mozilla.org/RapidRelease/Calendar

authors:

  lourcastillo:
    display_name: Lourdes Castillo
    title: Mozilla Reps & Review Team
    bio: Ingeniera en Informática, paraguaya viviendo en Chile. QA Engineer en Vacasa, empresa norteamericana en Chile. Mozilla Representative en Chile y Review team para la comunidad global. 
    avatar: lourcastillo.jpg
    web: https://community.mozilla.org/people/lourcastillo/
    github: lourcastillo

  skamel:
    display_name: Scarlett Melgarejo
    title: Equipo de Diseño
    bio: Diseño web y gráfico. Conocimientos en Vtex, Joomla, Wordpress, Magento, Open Cart, Moodle, HTML5, CSS3 y JS. Coordinadora y Relatora de Joomla, impartido en el Depto. de Informática de la Universidad de Santiago - USACH. Miembro de Mozilla Chile y encargada de PR desde el 2014. 
    avatar: skamel.jpg
    web: https://community.mozilla.org/en/people/skamel/
    github:

  Eduardo Urcullú:
    display_name: Eduardo Urcullú
    title: Mozilla Reps
    bio: Miembro fundador de Mozilla Paraguay y colaborador de Mozilla Hispano y Chile, evangelizador de Mozilla desde 2009. Representante de Mozilla desde junio de 2011.
    avatar: urcu.jpg
    web: https://reps.mozilla.org/u/Urcu/
    github: urcubot

  Miguel Pedreros:
    display_name: Miguel Pedreros
    title: Evangelización y Alfabetización Web
    bio: Miguel es un voluntario muy activo en la comunidad de Mozilla Chile realizando charlas sobre el manifiesto y la misión de mozilla en universidades chilenas.
    avatar: ocioslax.jpg
    web: https://community.mozilla.org/people/ocioslax/
    github: ocioslax

  Javier Martínez Ortiz:
    display_name: Javier Martínez Ortiz
    title: PR en Mozilla Chile
    bio: Periodista. Académico. Cocinero. Melómano. Encargado de PR en la comunidad Mozilla Chile.
    avatar: hyoga2k.jpg
    web: https://mozillians.org/en-US/u/hyoga2k/
    github:

  Gonzalo Perez:
    display_name: Gonzalo Perez
    title: Equipo de Desarrollo
    bio: Arquitecto de Software, Docente Universitario, Magister (c) Ing. de Sw, MVP Microsoft.
    avatar: chalalo.jpg
    web: https://community.mozilla.org/en/people/chalalo/
    github: chalalo1533

  ravmn:
    display_name: Richard von Moltke Necochea
    title: Localización es-CL
    bio: Estudiante de medicina, traductor voluntario y entusiasta de la tecnologia
    avatar: ravmn.jpg
    web: https://community.mozilla.org/people/ravmn/
    github: RAVMN

  mozilla:
    display_name: Mozilla
    Title:
    bio:
    avatar:
    web: https://mozillachile.cl
    github:

  iformas:
    display_name: Ignacio Formas
    title: Equipo de Desarrollo
    bio: 
    avatar: iformas.jpg
    web: https://community.mozilla.org/people/iformas/
    github: iformas
    
paginate: 12
excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-figure
