title: Mozilla Chile
description: Por un internet público, libre y accesible.
extradescription: Medio de difusión de actividades de Mozilla Chile
email: release-mgmt@mozilla.com
url: "https://mozillachile.cl"
github: "https://github.com/mozilla/release-blog"
highlighter: rouge
repository: https://github.com/mozillachile/blog

# Navigation
navigation:
- title: Twitter
  url: https://twitter.com/MozillaReleases
- title: Team Wiki
  url: https://wiki.mozilla.org/Release_Management
- title: Release Calendar
  url: https://wiki.mozilla.org/RapidRelease/Calendar

authors:
  iformas:
    display_name: Ignacio Formas
    web: https://community.mozilla.org/people/iformas/
    github: iformas

paginate: 12
excerpt_separator: "<!-- more -->"
